# Generated by Django 4.0 on 2022-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
